# Specific settings for the HireBase Manager
hire_base_manager:
  query_postfix: 'Intern' # optional

  # API PAYLOAD
  defaults:
    search_type: 'summary'
    accuracy: 'high'
    top_k: 10000  # because of date filter
    limit: 100
    page: 1
    # specifically Internships
    job_type:
      - 'Internship'