# Data Processing Pipline

# General rules
General:

  # ignore roles with certain features
  ignore:

    # ignore roles where position has tag
    position:
      - "graduate"
      - "ðŸŽ“"
      - "phd"

    # ignore roles where link has tag
    link:
      - "ðŸ”’"

  # forward fill chars that are considered null (for company name)
  scrubAndFfill:

    # chars to treat as null
    char:
      - "â†³"

# rules for sites
Specific:
  # note: the reason for this is for adding specific filters based off url
  # please do not add the same filters that are in general into specific
  #  just adds un-need complexity: just in case there is a check
  #
  #  Below is purely an example

  # used to identify which site this filter belongs to
  example.com1:   # this is the site id

    # ignore roles with certain features
    ignore:

      # ignore roles where position has tag
      position:
        - "graduate"
        - "ðŸŽ“"
        - "phd"

      # ignore roles where link has tag
      link:
        - "ðŸ”’"

    # forward fill chars that are considered null (for company name)
    scrubAndFfill:

      # chars to treat as null
      char:
        - "â†³"
