# Configuration of websites to parse

sites:

  # specification of websites
  - url: 'www.example.com/parser'
    robots: 'www.example.com/robots.txt'
    parser_type: ''
    date_formate: '--relative [formate]'

    # used to identify site for other pipelines
    site_id: 'example.com1'

    # desired job info is located
    selectors:

      # job meta-data
      company_name: "table tbody tr td:first-child"
      position: "table tbody tr td:nth-child(2)"
      link: "table tbody tr td:nth-child(5) a:first-child"
      date: "table tbody tr td:last-child"